"""
Django settings for m_challenge project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%+8nedny4sbl%v=@q*twiwhxf2o6m+sk#l(gkbjqkp5@=n98@2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #if set False development server won't work any more; but set it False when we deploy it

ALLOWED_HOSTS = []


# Application definition

######professtional way
#3333333333333333333333django does not know app "chalapp" exist so we need to make django aware about, so we need to officially register the app here(chalapp)
INSTALLED_APPS = [
    'chalapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',##########333333333333333333#use indirectly for detecting when sending back html and setting correct heading on response
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', ###########33333333333333this required to load the functionality it need to handle static files
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'm_challenge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        #######33333333333333333mostly for gobal templates which is used by multiple apps
        'DIRS': [
            #########33333333#BASE_DIR / "chalapp" / "templates"    #absolute path    "app name"/"folder"; django should look at this path when looking for templates
    
            BASE_DIR / "template"
        ],
        
        'APP_DIRS': True,####3333333333333333True mean while looking for template folder automatically look for template folder in app(here chalapp) folder.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'm_challenge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'  #3333333333needed to utilize static files

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#to make django aware of global static files
STATICFILES_DIRS = [
    ############3333333333333333333333333
    BASE_DIR / 'static'
]
